-- 코드를 입력하세요
SELECT ANIMAL_ID, t1.ANIMAL_TYPE, t1.NAME
FROM ANIMAL_INS t1 join ANIMAL_OUTS t2 using(ANIMAL_ID)
WHERE 
    t1.SEX_UPON_INTAKE LIKE "%Intact%" 
    AND (t2.SEX_UPON_OUTCOME LIKE "%Spayed%" OR t2.SEX_UPON_OUTCOME LIKE "%Neutered%")
ORDER BY ANIMAL_ID;