-- 코드를 입력하세요
SELECT t1.REST_ID, t1.REST_NAME, t1.FOOD_TYPE, t1.FAVORITES, t1.ADDRESS,ROUND(AVG(t2.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO t1 JOIN REST_REVIEW t2 ON t1.REST_ID = t2.REST_ID
WHERE LEFT(ADDRESS,2) = "서울"
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
