-- 코드를 입력하세요
SELECT t1.PRODUCT_ID, t1.PRODUCT_NAME, SUM(t2.AMOUNT*t1.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT t1 JOIN FOOD_ORDER t2 USING(PRODUCT_ID)
WHERE SUBSTRING(PRODUCE_DATE,6,2) = "05"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;