SELECT t1.ID, t2.FISH_NAME, t1.LENGTH
FROM FISH_INFO t1 JOIN FISH_NAME_INFO t2 on t1.FISH_TYPE = t2.FISH_TYPE
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_LENGTH
on t1.FISH_TYPE = MAX_LENGTH.FISH_TYPE AND t1.LENGTH = MAX_LENGTH.LENGTH
ORDER BY t1.ID ASC;
